name: Pipeline Continuous Integration

on:
  push:
    branches:
      - main
      - branche_tests_unitaires
  pull_request:
    branches:
      - main
      - branche_tests_unitaires

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Tests unitaires
        run: |
          pytest test.py


